version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: registry.vsamtuc.top
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: basic-realm
    service: 
    issuer:
    rootcertbundle:
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
