apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
  labels:
    kubernetes.io/metadata.name: docker-registry       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pv-claim
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 60Gi
  storageClassName: longhorn
