apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
  namespace: default
spec:
  http:
  - backends:
    - serviceName: httpbin
      servicePort: http
    match:
      hosts:
      - stelar.vsamtuc.top
      paths:
      - /foo/*
    name: testroute1
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri:
        - "/foo/(.*)"
        - "/$1"
